web_app/pr_main/main/__init__.py
"""
    AUTHOR: Sutharsan Rajaratnam
    DATE: December 16, 2020
    APPLICATION: Payroll Web Application
    PURPOSE: 
    NOTE: 

    FILE: payroll/main/__init__.py

"""

from flask import Blueprint

#Define blueprint
blueprint_main   = Blueprint('main', __name__, url_prefix='/main',
                            template_folder='templates',
                            static_folder='static')

from . import views

web_app/pr_main/main/views.py
"""
    AUTHOR: Sutharsan Rajaratnam
    DATE: November 17, 2019
    APPLICATION: Payroll Web Application
    FILE: payroll/web_app/main/views.py
    PURPOSE: The main application file to run the "Payroll Report" web application
    
    NOTE: Explicitly excluded using 'SQLAlchemy' (Python SQLtoolkit & ORM), wanted to maintain non-Python universal readability. 
"""

import os
from datetime import datetime
from flask import Flask, flash, render_template, request, redirect
from werkzeug.utils import secure_filename

"""
    Import configuration (NOTE: Relative import)
"""
#from .config import app, mysql
from ..config import conf

app     = conf.app
mysql   = conf.mysql

"""
    Import custom modules.
"""
from . import modules as m

"""
    Import registered Blueprint.
"""
from . import blueprint_main as main

DB_TB_NAMES    = {
                    "tb_timesheet":     app.config['DB_TABLE_TIME_REPORT'], 
                    "tb_payroll":       app.config['DB_TABLE_PAYROLL_REPORT'],
                    "tb_ts_history":    app.config['DB_TABLE_TIMESHEET_HISTORY'],
                    "tb_history":       app.config['DB_TABLE_PAYROLL_HISTORY']
                }


#ROUTE: Default (ie.'homepage') route for web application
#@app.route("/")
@main.route("/")
def home():
    m.db.db_op.db_tb_init(mysql, DB_TB_NAMES)
    tb_data_csv = m.db.db_op.get_tb(mysql, app.config['DB_TABLE_TIME_REPORT'])    
    return render_template("/home.html", tb_tr_data=tb_data_csv)

#ROUTE: Provides brief overview of web application.
@main.route("/about")
def about():
    return render_template("about.html")


#ROUTE: Upload timesheet files to server.
@main.route('/', methods=['POST'])
def upload():
#    print "STEP 1:    Upload Data File "
    print ("TEST---1")
    process_upload()
    print ("TEST---2")
    return redirect('/main')


#ROUTE: Shows processed payroll report based on all uploaded timesheets.
@main.route("/payrollreport")
def payrollReport():    
    db_pr_list = m.db.db_op.get_tb_data_order_01(mysql, app.config['DB_TABLE_PAYROLL_REPORT'])
    return render_template("payrollreport.html", tb_csvData=db_pr_list)


#ROUTE: Shows history of raw timesheet data from all successfully uploaded timesheets.
@main.route("/timesheethistory")
def timesheetHistory(): 
    db_ts_history_list = m.db.db_op.get_tb_data_order_02(mysql, app.config['DB_TABLE_TIMESHEET_HISTORY'])
    return render_template("ts_history.html", tb_data=db_ts_history_list)


#ROUTE: Resets all server side tables listed in 'DB_TB_NAMES' dictionary above.
@main.route("/reset")
def reset():
    m.db.db_op.db_tb_reset(mysql, DB_TB_NAMES)
    return redirect('/main')


"""
    Local support functions that call relevant custom application functions defined elsewhere 
    in the 'modules' folder    
"""

def process_upload():
    filepath        = app.config['UPLOAD_PATH']
    if request.method == 'POST':
        # check if the post request has the file part
        if 'file' not in request.files:
            flash('No file part')
            #return redirect(request.url)
            return redirect('/main')
        file = request.files['file']
        if file.filename == '':
            flash('No file selected for uploading')
            #return redirect(request.url)
            return redirect('/main')
        if file and m.upload.allowed_file(file.filename, app.config['ALLOWED_EXTENSIONS']):
            m.upload.upload_file(app.config['UPLOAD_PATH'], file)
            flash('File successfully uploaded', 'success')
            csvData_list, report_id = process_csv(filepath, file.filename)
            db_update_database(csvData_list, report_id)
            process_payroll(report_id) 
        else:
            flash('Allowed file types only: .csv')
            #return redirect(request.url)
            return redirect('/main')
               
def process_csv(filepath, filename):
    
#    print "STEP 2:    Process CSV "
    csvData_list, csvData_footer = m.csvReader.importCSVUpload_dict(filepath, filename)
    report_id = int(csvData_footer[0]["hours worked"])
    return csvData_list, report_id


def db_update_database(csvData_list, report_id):    
    
#    print "STEP 3:    Update Table "
    
    #NOTE - PRODUCTION RELEASE: Remove 'tb_payroll' from the dictionary after testing 
    tb_names_drop = {
                "tb_timesheet":     app.config['DB_TABLE_TIME_REPORT'], 
                "tb_payroll":       app.config['DB_TABLE_PAYROLL_REPORT']
                } 
    
    code, str = m.db.db_op.db_update_database(mysql, csvData_list, report_id, DB_TB_NAMES, tb_names_drop)
    if (code == 111):
        msg = "New report successfully added to database"
        flash(msg, 'success')
    elif (code == 333):
        msg = "ERROR: Report ID '%s' already exists - Timesheet rejected!" %(str)
        flash(msg, 'error')
    elif (code == 000):
        msg = "ERROR: Failed to insert data into table: '%s'" %(str)
        flash(msg, 'error')
    else:
        msg = "ERROR - DATABASE UPDATE: Unknown code!"
        flash(msg, 'error')
    
    
def process_payroll(report_id):
#    print "===== PROCESS PAYROLL ====="
    m.pay.compute_payroll(app, mysql, report_id)


#Enables this view file to be executed directly as a 'solo' standalone flask application.    
if __name__ == "__main__":
    app.run(debug=True)

web_app/pr_main/main/templates/home.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
	<head>
		<meta charset="utf-8">
		<title>Home</title>
	</head>
	<body>
		{% extends "template.html" %}
		{% block content %}
		
		<br>
		<h2> Upload Timesheet Report 
			<h3>(ie. timesheet .csv file)</h3>
		</h2>
		<p>
			{% with messages = get_flashed_messages(with_categories=true) %}
				{% if messages %}
					<ul class=flashes>
						{% for category, message in messages %}
							<div class="{{ category }}">
								<li>{{ message }}</li>
							</div>
						{% endfor %}
					</ul>
				{% endif %}
			{% endwith %}
		</p>
		
		<div class="container">
			<table>
				<thead>
					<tr >
						<th style="width: 50%">
							<form method="POST" action="{{ url_for('main.home') }}" enctype="multipart/form-data">
							    <dl>
									<p><input type="file" name="file" autocomplete="off" required></p>
							    </dl>
							    <p><input type="submit" value="Submit"></p>
							</form>
						</th>
						<th style="width: 50%">
							<div class="container" align="RIGHT">
								<h3> <b>OPTION</b> - Reset All Tables </h3>
								<form action="{{ url_for('main.reset') }}" method="GET">
									<div style="float:top;margin-right:20px;">
										<label > Reset all server side tables</label>
									</div>
									<div style="float:top;margin-right:20px;">
										<input type="submit" class="btn btn-danger" value="RESET"></input>
									</div>
								</form>
							</div>			
						</th>
					</tr>
				</thead>
			</table>
		</div>
		
		<br>
		<small class="text-muted"> Timesheet Report </small>
		<p> <b>NOTE:</b> Reflects most recent timesheet upload only </p>
		
		<div >
			<table class="table table-striped table-hover table-condensed" id="owned_stock_table" >
				<thead>
					<tr>
						<th style="width:25%; text-align:center">date</th>
						<th style="width:25%; text-align:center">hours worked</th>
						<th style="width:25%; text-align:center">employee id </th>
						<th style="width:25%; text-align:center">job group</th>
					</tr>
				</thead>
			</table>
			<div class="bodycontainer scrollable">
				<table class="table table-striped table-condensed table-scrollable" id="owned_stock_table" >
					<tbody>
						{% for row in tb_tr_data %}
						<tr>
							<td style="width: 25%; text-align:center">{{row['date']}}</td>
							<td style="width: 25%; text-align:center">{{row['hours_worked']}}</td>
							<td style="width: 25%; text-align:center">{{row['employee_id']}}</td>
							<td style="width: 25%; text-align:center">{{row['job_group']}}</td>
						</tr>
						{% endfor %}
					</tbody>
				</table>
			</div>
		</div>
		
		
		{% endblock %}
	</body>
</html>

web_app/pr_main/main/templates/template.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
	<head>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
		
		<!-- Bootstrap CSS -->
		<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
		<link rel="stylesheet" href="/static/custom.css" type="text/css">
		<title>Flask Parent Template</title>
	</head>
	<body>
		<header>
			<div >
				<h1 class="logo">PAYROLL SYSTEM - prototype</h1>
				<strong><nav>
				<ul class="menu">
					<li><a href="{{ url_for('main.home') }}">Home</a></li>
					<li><a href="{{ url_for('main.payrollReport') }}">Payroll Report</a></li>
					<li><a href="{{ url_for('main.timesheetHistory') }}">Timesheet History</a></li>
				</ul>
				</nav></strong>
			</div>
		</header>
    
		{% block content %}
		{% endblock %}
	
		<!-- Optional JavaScript -->
		<!-- jQuery first, then Popper.js, then Bootstrap JS -->
		<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
		<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
		<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
	</body>
</html>